# SPDX-FileCopyrightText: 2024 Nicco Kunzmann <niccokunzmann@rambler.ru>
#
# SPDX-License-Identifier: LicenseRef-mine

baseURL = 'https://CosmicEarthMedicine.co.uk/'
noBuildLock = true
languageCode = 'en-uk'
title = 'Cosmic Earth Medicine'
theme = 'hugo-universal-theme'
enableGitInfo = true

## See https://github.com/devcows/hugo-universal-theme
## See https://github.com/devcows/hugo-universal-theme/blob/master/exampleSite/config.toml

[params]
    style = 'violet'

    ## Logo, see https://github.com/devcows/hugo-universal-theme?tab=readme-ov-file#logo
    disabled_logo = true
    logo_text = "Cosmic Earth Medicine"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

    dropdown_mouse_over = true
    copyright = "Copyright (c) 2024, Yemaya Rodriguez and Nicco Kunzmann; all rights reserved."
    date_format = "January 2, 2006"

    formspree_action = "https://formspree.io/f/xpwzpoar"
    email = "yemaya.earthing@proton.me"
    contact_form_ajax = false
    enableRecaptchaInContactForm = true
    googleRecaptchaKey = "6LfpknMqAAAAAJ9zYYIttHIwGudXJcMgveyFbUnv"

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

#[[params.menu]]
#    name = "Contact"
#    url  = "/contact"
#    weight = 4

[[menu.main]]
    name       = "Home"
    identifier = "section.ap-home"
    url        = "/"
    weight     = 1
#    post       = 1

[[menu.main]]
    name       = "Sound"
    identifier = "section.ap-sound-medicine"
    url        = "/sound-medicine/"
    weight     = 2

[[menu.main]]
    name       = "Contact"
    identifier = "section.ap-contact"
    url        = "/contact/"
    weight     = 3


[params.topbar]
    enable = true
    text = ""
    #"<p>Contact Yemaya on <a href='tel:+447540951912'>+44 7540 951 912</a></p>"

[[menu.topbar]]
    weight = 20
    name = "GitHub"
    url = "https://github.com/niccokunzmann/CosmicEarthMedicine"
    pre = '<i class="fa-brands fa-2x fa-github"></i>'

[[menu.topbar]]
    weight = 1
    name = "Instagram"
    url = "https://www.instagram.com/cosmic_earth_medicine_"
    pre = '<i class="fa-brands fa-2x fa-instagram"></i>'

[[menu.topbar]]
    weight = 4
    name = "Phone"
    url = "tel:+447540951912"
    pre = '<i class="fa-solid fa-2x fa-phone"></i>'

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:yemaya.earthing@proton.me"
    pre = '<i class="fa-regular fa-2x fa-envelope"></i>'

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://m.facebook.com/yemrodriguez.735/"
    pre = '<i class="fa-brands fa-2x fa-facebook"></i>'

[[menu.topbar]]
    weight = 2
    name = "Whatsapp"
    url = "https://wa.me/+447540951912"
    pre = '<i class="fa-brands fa-2x fa-whatsapp"></i>'

[[menu.topbar]]
    weight = 2
    name = "Telegram"
    url = "https://t.me/yem_aya"
    pre = '<i class="fa-brands fa-2x fa-telegram"></i>'


[privacy]
# see https://gohugo.io/about/privacy/
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

