# SPDX-FileCopyrightText: 2024 2024 Nicco Kunzmann and Open Web Calendar Contributors <https://open-web-calendar.quelltext.eu/>
#
# SPDX-License-Identifier: GPL-2.0-only

# Run pytest for each commit.
# See also
#    https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#running-tests-with-tox
name: "Build & Test"

on: [push]

# cancel builds in progress if a new push has been made to the same ref
# see https://stackoverflow.com/a/70972844/1320237
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

jobs:
  reuse:
    name: "Run licensing tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install tox
        run: pip install tox
      - name: Run tests
        # Run tox using the version of Python in `PATH`
        run: tox -e reuse

  # link-check:
  #   name: "Check Links in Documentation"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0 # required for mkdocs git date, see  https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-environments
  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.11
  #     - name: Install tox
  #       run: pip install tox linkchecker
  #     - name: Check Links
  #       run: scripts/check-links-in-documentation.sh
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: checked-links.html
  #         path: linkchecker-out.html
